# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    - name: Yarn setup
      uses: actions/checkout@v2
      with: 
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    #- name: Use Node.js ${{ matrix.node-version }}
    #  uses: actions/setup-node@v3
    #  with:
    #    node-version: ${{ matrix.node-version }}
    #    cache: 'npm'
    - run: npm install   
    - run: npm install -g yarn
    - run: yarn start
    
    #- run: yarn run build -if--present

    #- name: Configure AWS Credential
    #  uses: Neeraj9419/SnapShot@master
    #  with:
    #    args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
    #  env:
    #      AWS_S3_BUCKET: 'myreactappbucket'
    #      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #      AWS_REGION: ${{ secrets.AWS_REGION }} # optional: defaults to us-east-1
            
 #   - name: Upload to s3
 #     run: aws s3 cp ./SnapShot/build s3://myreactappbucket --recursive
      
